In [7]:
import sys
sys.path.append('../')
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler
import tensorflow.compat.v1 as tf 
tf.compat.v1.disable_eager_execution()
import re
import numpy as np
from sklearn.preprocessing import LabelEncoder 
le  = LabelEncoder()
std = MinMaxScaler()
#std = StandardScaler()
df = pd.read_csv('../datasets/diabetes _raw/diabetes.csv')
for col in df.columns[:-1]:
        bins = np.linspace(df[col].min(), df[col].max(), 10)
        df[col]=pd.cut(df[col], bins, labels =[1,2,3,4,5,6,7,8,9], include_lowest=True )
#df.to_csv('../datasets/diabetes.csv', index=False)

In [8]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,4,7,6,4,1,5,3,5,1
1,1,4,5,3,1,4,2,2,0
2,5,9,5,1,1,4,3,2,1
3,1,5,5,3,1,4,1,1,0
4,1,7,3,4,2,6,9,2,1
...,...,...,...,...,...,...,...,...,...
763,6,5,6,5,2,5,1,7,0
764,2,6,6,3,1,5,2,1,0
765,3,6,6,3,2,4,1,2,0
766,1,6,5,1,1,5,2,4,1
767,1,5,6,3,1,5,1,1,0